### ISSUE TITLE
Usage with react-router

### ISSUE THREAD

**Issue by miroli** [abramz/gulp-render-react#1]
Great plugin!

I have an app that I want to render to static markup, but the app is initialized using `react-router`.

``` javascript
// routes.jsx
var routes = (
  <Route path="/" component={App}>
    <IndexRoute component={Form} />
    <Route path='about' component={Result} />
  </Route>
);
```

This is the app component that I want to render. As you can see, it needs to be passed child components to render. But how do I pass them to `App` using this plugin?

``` javascript
var App = React.createClass({
  render: function() {
    return (
      <div>
        <h1>App</h1>
        {this.props.children}
      </div>
    );
  }
});
```

**Comment by abramz** [comment]
Good question. That is something I hadn't  considered so I do not know if it is possible to do now. That being said, give me some time to see if I can't figure something out for you.

**Comment by abramz** [comment]
Sorry this has taken so long, I have been super busy. I plan on looking into this tonight.

**Comment by abramz** [comment]
Sorry this took awhile, you should be able to use this with react-router if you implement a component to wrap the router. You also need to use the in-memory history as well. I have updated the [readme](https://github.com/abramz/gulp-render-react#usage-with-react-router) (accompanied by [tests](https://github.com/abramz/gulp-render-react#usage-with-react-router)) with an example.

Please note, I have just updated the package in [npm](https://www.npmjs.com/package/gulp-render-react) as well.
