### ISSUE TITLE
caching issue?

### ISSUE THREAD

**Issue by zebapy** [abramz/gulp-render-react#7]
I'm trying to use this plugin to develop some static files, but I'm encountering some issue where the HTML output files are not updated unless I restarted gulp (gulp watch is run by default in my code)

https://github.com/zebapy/react-gulp-emails

TBH I don't know if this is just an issue with my code or this plugin, but I'm hoping to get some insight. 

Reproduction:
1. Follow getting started steps in readme
2. Open browser sync `localhost:3000`
3. Navigate to example email (`/communications/comms-newsletter.html`)
4. Edit the example email from `test` to something else

Expected:
- Browser should reflect the changed text
- `dist` folder should have updated html file with new text

Result:
- No change

If you stop gulp and restart it, the html file will be updated correctly.

**Comment by abramz** [comment]
I will try to take a look this weekend

**Comment by abramz** [comment]
Hey @zebapy, I opened a PR on your repo w/ a fix to the `gulpfile` which should resolve your issues.

I do not like that you have to pass the scripts through `babel` before `gulp-render-react` can process them. I will look into the possibility of ingesting `babel` files as well.

**Comment by zebapy** [comment]
@abramz, Thanks so much for taking the time to look at this. Sadly, I'm not seeing the PR resolve the issue. I still have the same problem. Did you successfully have the browsersync update and the HTML files become updated with correct code?

As far as adding babel transpiling to this plugin, I think it'd be best to keep that separate? From what I understand about gulp plugins, they really strive for single purpose. I like the separation for this when there's already babelify.

**Comment by abramz** [comment]
Yep, and it logs to the console that the file was updated

**Comment by zebapy** [comment]
This is what I'm experiencing. ![gulpreact](https://cloud.githubusercontent.com/assets/2199845/21299856/802c6686-c56d-11e6-889f-cc7d8020b333.gif)

**Comment by abramz** [comment]
I'll check it out later tonight

**Comment by zebapy** [comment]
Thanks again. I'd be interested in seeing an example/ directory in this repo as the readme doesn't cover babel files, and what I have in my repo is my best guess to handling babel transpiling, but it obviously has an issue currently.

**Comment by zebapy** [comment]
I made another branch to test the basics (no babel) and it seems watching for changes the rebuilding just isn't working for me still. https://github.com/zebapy/react-gulp-emails/tree/gulp-react-example

**Comment by abramz** [comment]
I updated my PR on your repo, I have a new version of the module up that fixes the issue.

The way the module currently works, you would need to run `gulp` with babel in order to `require` es6 files. This is a limitation due to the module's use of `require`. You can see from the tests that it can ingest them just fine when doing this.

As per the guidelines of this module, it does 1 thing, render React components as strings. It does not deal with anything else because that is the philosophy of the gulp ecosystem. 

This is an open source module. If you would like to change the way the the module ingests files or add documentation, feel free to open a PR with the changes. Otherwise I will add enhancements as I have time to do so.

resolved by #12

**Comment by zebapy** [comment]
I hadn't considered needing to use babel CLI to run gulp first, that makes sense. 

I may have misinterpreted what you previously said, I agree the module should serve a single purpose (only transforming react components into static html) instead of also transpiling babel (besides running babel to run gulp).

Thanks so much for this. Interesting to see it was an actual cache issue.
